### ISSUE TITLE
InsufficientLen error

### ISSUE THREAD

**Issue by avently** [PrivateRookie/ws-tool#17] opened 2022-06-17 20:32 UTC
Hello. Thanks for such performant and easy-to-use library. 
I'm trying to adapt it for using with large streams from Binance and getting an error: Close code: 1008, error: InsufficientLen(2). So 5-10 seconds it works fine, I see messages from websocket. But after that I see this error.
```rust
Err(e) => match e {
            WsError::ProtocolError { close_code, error } => {
              println!("Close code: {close_code:?}, error: {error:?}");
              break
            }
            _ => {
              println!("Something strange happened with the websocket");
            }
          }
```

I'm just doing `client.receive().await` without sending anything. Do you known what can be a cause?

I use this url which produce this error after a couple of seconds:

```
wss://fstream.binance.com:443/stream?streams=rayusdt@bookTicker/api3usdt@bookTicker/sushiusdt@bookTicker/cvcusdt@bookTicker/btsusdt@bookTicker/ftmbusd@bookTicker/hotusdt@bookTicker/trxbusd@bookTicker/zrxusdt@bookTicker/qtumusdt@bookTicker/iotausdt@bookTicker/btcbusd@bookTicker/wavesusdt@bookTicker/adausdt@bookTicker/litusdt@bookTicker/xtzusdt@bookTicker/bnbusdt@bookTicker/darusdt@bookTicker/hntusdt@bookTicker/etcusdt@bookTicker/xmrusdt@bookTicker/yfiusdt@bookTicker/fttbusd@bookTicker/ethusdt@bookTicker/aliceusdt@bookTicker/alphausdt@bookTicker/woousdt@bookTicker/sfpusdt@bookTicker/reefusdt@bookTicker/batusdt@bookTicker/dogeusdt@bookTicker/trxusdt@bookTicker/rlcusdt@bookTicker/storjusdt@bookTicker/snxusdt@bookTicker/1000xecusdt@bookTicker/dotbusd@bookTicker/audiousdt@bookTicker/nearbusd@bookTicker/xlmusdt@bookTicker/apebusd@bookTicker/iotxusdt@bookTicker/neousdt@bookTicker/unfiusdt@bookTicker/sandusdt@bookTicker/dashusdt@bookTicker/kavausdt@bookTicker/runeusdt@bookTicker/apeusdt@bookTicker/ctkusdt@bookTicker/linkusdt@bookTicker/celrusdt@bookTicker/bnxusdt@bookTicker/opusdt@bookTicker/rsrusdt@bookTicker/adabusd@bookTicker/dgbusdt@bookTicker/sklusdt@bookTicker/renusdt@bookTicker/lptusdt@bookTicker/jasmyusdt@bookTicker/tomousdt@bookTicker/mtlusdt@bookTicker/ltcusdt@bookTicker/dodobusd@bookTicker/egldusdt@bookTicker/ksmusdt@bookTicker/bnbbusd@bookTicker/ontusdt@bookTicker/vetusdt@bookTicker/imxusdt@bookTicker/trbusdt@bookTicker/manausdt@bookTicker/flowusdt@bookTicker/cotiusdt@bookTicker/chrusdt@bookTicker/bakeusdt@bookTicker/avaxbusd@bookTicker/grtusdt@bookTicker/flmusdt@bookTicker/galusdt@bookTicker/galabusd@bookTicker/maskusdt@bookTicker/eosusdt@bookTicker/ognusdt@bookTicker/ethusdt_220624@bookTicker/galbusd@bookTicker/balusdt@bookTicker/stmxusdt@bookTicker/dentusdt@bookTicker/kncusdt@bookTicker/srmusdt@bookTicker/enjusdt@bookTicker/c98usdt@bookTicker/zenusdt@bookTicker/atomusdt@bookTicker/nearusdt@bookTicker/solbusd@bookTicker/ensusdt@bookTicker/bchusdt@bookTicker/atausdt@bookTicker/iostusdt@bookTicker/hbarusdt@bookTicker/luna2busd@bookTicker/zecusdt@bookTicker/1000shibusdt@bookTicker/tlmbusd@bookTicker/antusdt@bookTicker/ethbusd@bookTicker/galausdt@bookTicker/aaveusdt@bookTicker/gtcusdt@bookTicker/algousdt@bookTicker/lrcusdt@bookTicker/avaxusdt@bookTicker/arpausdt@bookTicker/celousdt@bookTicker/roseusdt@bookTicker/maticusdt@bookTicker/1inchusdt@bookTicker/mkrusdt@bookTicker/peopleusdt@bookTicker/ancbusd@bookTicker/thetausdt@bookTicker/uniusdt@bookTicker/linausdt@bookTicker/arusdt@bookTicker/rvnusdt@bookTicker/filusdt@bookTicker/nknusdt@bookTicker/klayusdt@bookTicker/defiusdt@bookTicker/compusdt@bookTicker/btcdomusdt@bookTicker/solusdt@bookTicker/btcusdt@bookTicker/omgusdt@bookTicker/icxusdt@bookTicker/icpbusd@bookTicker/blzusdt@bookTicker/gmtusdt@bookTicker/ftmusdt@bookTicker/bandusdt@bookTicker/xrpbusd@bookTicker/dogebusd@bookTicker/xrpusdt@bookTicker/fttusdt@bookTicker/sxpusdt@bookTicker/crvusdt@bookTicker/belusdt@bookTicker/dotusdt@bookTicker/xemusdt@bookTicker/gmtbusd@bookTicker/oneusdt@bookTicker/1000luncbusd@bookTicker/zilusdt@bookTicker/axsusdt@bookTicker/dydxusdt@bookTicker/oceanusdt@bookTicker/chzusdt@bookTicker/ankrusdt@bookTicker/duskusdt@bookTicker/btcusdt_220624@bookTicker/ctsiusdt@bookTicker
```

Using this url with OkHttp client (Java VM) without any issues.

**Comment by PrivateRookie** [comment] 2022-06-17 23:40
I can't reproduce the bug on wsl2 ubuntu 20.0, can you give me your machine's operating system information and kernel tcp setting?

**Comment by avently** [comment] 2022-06-18 00:02
Maybe it's important to say that I start >10 large streams simultaneously (using async task) and all of them ends with some errors. I started now and got `Close code: 1008, error: InvalidLeadingBits(1)` error. Here is a file with all urls I started with, maybe it will help to reproduce the problem:  
[wss.txt](https://github.com/PrivateRookie/ws-tool/files/8931827/wss.txt)


Manjaro (Archlinux based), kernel 5.14.18-1

`sudo sysctl -a | grep tcp`
```
net.ipv4.tcp_abort_on_overflow = 0
net.ipv4.tcp_adv_win_scale = 1
net.ipv4.tcp_allowed_congestion_control = reno cubic
net.ipv4.tcp_app_win = 31
net.ipv4.tcp_autocorking = 1
net.ipv4.tcp_available_congestion_control = reno cubic
net.ipv4.tcp_available_ulp = espintcp mptcp
net.ipv4.tcp_base_mss = 1024
net.ipv4.tcp_challenge_ack_limit = 1000
net.ipv4.tcp_comp_sack_delay_ns = 1000000
net.ipv4.tcp_comp_sack_nr = 44
net.ipv4.tcp_comp_sack_slack_ns = 100000
net.ipv4.tcp_congestion_control = cubic
net.ipv4.tcp_dsack = 1
net.ipv4.tcp_early_demux = 1
net.ipv4.tcp_early_retrans = 3
net.ipv4.tcp_ecn = 2
net.ipv4.tcp_ecn_fallback = 1
net.ipv4.tcp_fack = 0
net.ipv4.tcp_fastopen = 1
net.ipv4.tcp_fastopen_blackhole_timeout_sec = 0
net.ipv4.tcp_fastopen_key = 00000000-00000000-00000000-00000000
net.ipv4.tcp_fin_timeout = 60
net.ipv4.tcp_frto = 2
net.ipv4.tcp_fwmark_accept = 0
net.ipv4.tcp_invalid_ratelimit = 500
net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_time = 7200
net.ipv4.tcp_l3mdev_accept = 0
net.ipv4.tcp_limit_output_bytes = 1048576
net.ipv4.tcp_low_latency = 0
net.ipv4.tcp_max_orphans = 65536
net.ipv4.tcp_max_reordering = 300
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_max_tw_buckets = 65536
net.ipv4.tcp_mem = 142245       189662  284490
net.ipv4.tcp_migrate_req = 0
net.ipv4.tcp_min_rtt_wlen = 300
net.ipv4.tcp_min_snd_mss = 48
net.ipv4.tcp_min_tso_segs = 2
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_mtu_probe_floor = 48
net.ipv4.tcp_mtu_probing = 0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_no_ssthresh_metrics_save = 1
net.ipv4.tcp_notsent_lowat = 4294967295
net.ipv4.tcp_orphan_retries = 0
net.ipv4.tcp_pacing_ca_ratio = 120
net.ipv4.tcp_pacing_ss_ratio = 200
net.ipv4.tcp_probe_interval = 600
net.ipv4.tcp_probe_threshold = 8
net.ipv4.tcp_recovery = 1
net.ipv4.tcp_reflect_tos = 0
net.ipv4.tcp_reordering = 3
net.ipv4.tcp_retrans_collapse = 1
net.ipv4.tcp_retries1 = 3
net.ipv4.tcp_retries2 = 15
net.ipv4.tcp_rfc1337 = 0
net.ipv4.tcp_rmem = 10240       87380   12582912
net.ipv4.tcp_rx_skb_cache = 0
net.ipv4.tcp_sack = 1
net.ipv4.tcp_slow_start_after_idle = 1
net.ipv4.tcp_stdurg = 0
net.ipv4.tcp_syn_retries = 6
net.ipv4.tcp_synack_retries = 5
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_thin_linear_timeouts = 0
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_tso_win_divisor = 3
net.ipv4.tcp_tw_reuse = 2
net.ipv4.tcp_tx_skb_cache = 0
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_wmem = 10240       87380   12582912
net.ipv4.tcp_workaround_signed_windows = 0
net.mptcp.add_addr_timeout = 120
net.mptcp.allow_join_initial_addr_port = 1
net.mptcp.checksum_enabled = 0
net.mptcp.enabled = 1

```

**Comment by PrivateRookie** [comment] 2022-06-18 02:13
I made a stupid mistake while pre-parsing the frame header, it was fixed in version 0.5.4 and released. Please modify the ws-tool version in the project and test again

**Comment by avently** [comment] 2022-06-18 05:07
InvalidLeadingBits(1) still here. Behavior is not changed: all sockets receives this error after a couple of seconds. Don't you have such error? 
P.S. Cargo definitely uses new version, I checked updated source.

**Comment by avently** [comment] 2022-06-18 05:54
I found why we have different results with you. I have two test functions one of which uses client.receive(), and another - 
```
let (mut tx, mut rx) = client.split();
match rx.receive() {...}
```
First one after your fix works correctly while the second fails immediately. Do I use `split()` incorrectly?

**Comment by PrivateRookie** [comment] 2022-06-18 07:45
I found the cause of the problem. When implementing WsStream tls Split, I split the underlying stream to get the read/write half, but due to tls encryption, I get data that has not been decrypted, so an error will be reported directly. But TlsStream split API has not made any progress, and using tokio::io::split may be unsound, so sorry, the split function under wss may not be fixed. see this [issue](https://github.com/tokio-rs/tls/issues/40)

**Comment by avently** [comment] 2022-06-18 10:39
ok, will try to find a workaround then. This issue can be closed since you fixed it. Thanks, it was fast!

**Closed** 2022-06-18 10:39 UTC
